Repository NhiSty/challenge-stack-1, pull requests merged in 2023-02, with the labels that each got.

#35 Finished bcrud and fcrud
  .env.example
  config/services.yaml
  src/Maker/BackCrudMaker.php
  src/Maker/FrontCrudMaker.php
  src/Maker/Resources/config/makers.xml
  src/Maker/Resources/config/services.xml
  src/Maker/Resources/doc/index.rst
  src/Maker/Resources/help/MakeCrud.txt
  src/Maker/Resources/skeleton/Class.tpl.php
  src/Maker/Resources/skeleton/crud/controller/Controller.tpl.php
  src/Maker/Resources/skeleton/crud/templates/_delete_form.tpl.php
  src/Maker/Resources/skeleton/crud/templates/_form.tpl.php
  src/Maker/Resources/skeleton/crud/templates/edit.tpl.php
  src/Maker/Resources/skeleton/crud/templates/index.tpl.php
  src/Maker/Resources/skeleton/crud/templates/new.tpl.php
  src/Maker/Resources/skeleton/crud/templates/show.tpl.php
  src/Maker/Resources/skeleton/crud/test/Test.EntityManager.tpl.php
  src/Maker/Resources/skeleton/crud/test/Test.tpl.php
Labels: BACK

#51 Add new entities (NecessaryDocument & Demand)
  migrations/Version20230203114819.php
  src/Entity/Demand.php
  src/Entity/NecessaryDocument.php
  src/Entity/User.php
  src/Repository/DemandRepository.php
  src/Repository/NecessaryDocumentRepository.php
Labels: BACK

#52 Feature/20
  package-lock.json
  templates/Back/registration/register.html.twig
  templates/base.html.twig
  templates/security/login.html.twig
  webpack.config.js
Labels: FRONT

#54 Front page reset password
  templates/reset_password/request.html.twig
Labels: FRONT

#57 Fix bug on search bar + add search bar in results page
  src/Controller/SearchController.php
  src/Repository/ClinicRepository.php
  src/Repository/SpecialityRepository.php
  templates/search/index.html.twig
Labels: FRONT, BACK
